### ISSUE TITLE
Resource temporarily unavailable error on linux

### ISSUE THREAD

**Issue by htmlcsjs** [HactarCE/Hyperspeedcube#28]
`Error sending request: Resource temporarily unavailable` is the full error, nothing else is given in the output. 
![image](https://user-images.githubusercontent.com/46023024/210604112-d5b6a1fc-3b66-4f35-a00e-fc6f482593f6.png)
I am using wayland if that helps

**Comment by HactarCE** [comment]
Thank you for the report, and I'm sorry it took so long for me to reply! Can you try `RUST_LOG=trace ./hyperspeedcube > log.txt` and send the log?

I'm guessing this has something to do with graphics. It's also possible that v1.0.5 will fix the issue, since I made some changes there related to requesting the graphics adapter.

**Comment by htmlcsjs** [comment]
hmm updating it did fix the issue, atleast using `cargo run --release`
