### ISSUE TITLE
Settings > View > Projection > 3D FOV allows negative values with screwy results

### ISSUE THREAD

**Issue by cutelyaware** [HactarCE/Hyperspeedcube#45]
Tymon F has been publishing solution videos with projections that have been driving me nuts. We found out that it's because he's had his 3D FOV set to -15 degrees. (EG https://www.youtube.com/watch?v=BnwRGlPwgs4). It should be clamped to zero (or 1 like is currently done for the 4D FOV). 

![HSC negative FOV](https://github.com/HactarCE/Hyperspeedcube/assets/838809/6d2e6273-d190-4f9f-a3df-2e2f4eccf715)

**Comment by HactarCE** [comment]
This is an intentional feature. It's useful for demonstrating the 4D projection on a 3D puzzle. There's two ways to interpret MC4D-style projection: positive 4D FOV with hidden frontfaces, or negative 4D FOV with hidden backfaces. HSC allows both in 3D (see the "unfolded front" and "unfolded back" view presets).

Tymon's selection of projection parameters is their choice.

**Comment by cutelyaware** [comment]
It's your call of course, and it's better if it is within your intentioned use cases rather than a simple bug. I just find it really weird. For example "front face culling" is useful for things like 3D objects with 2D graphs projected onto the back faces of bounding boxes, though this is nothing like that. Notice also that you are culling front "cells", but not the front faces of the visible back cells. And since I don't really understand your intentions, I don't have any suggestions. I just wanted to report what looked to be a bug.
